version: '3'
services:
  api:
    build: ./api
    environment:
    - GOOGLE_APPLICATION_CREDENTIALS=/gcp/creds.json
    - NODE_ENV=development
    volumes:
    - ./creds.json:/gcp/creds.json
    - ./config.json:/app/config.json
    - ./api/src:/app/src
    entrypoint: bash -c "npm i -D && npm run start"
  batch:
    build: ./batch
    environment:
    - GOOGLE_APPLICATION_CREDENTIALS=/gcp/creds.json
    volumes:
    - ./creds.json:/gcp/creds.json
    - ./config.json:/app/config.json
    entrypoint: bash -c "npm i -g nodemon && nodemon ."
  ux:
    build: ./ux
    environment:
    - NODE_ENV=development
    volumes:
    - ./ux/src:/app/src
    - ./ux/pages:/app/pages
    - ./ux/components:/app/components
    - ./ux/static:/app/static
    - ./ux/next.config.js:/app/next.config.js
    entrypoint: ash -c "npm i -D && npm run dev"
  account:
    image: dougrich/oauth-aggregator
    volumes:
    - ./config.auth.json:/app/config.json
  gateway:
    build: ./gateway
    ports:
    - 80:80