version: '3'
services:
  batch:
    build: ./batch
    environment:
    - GOOGLE_APPLICATION_CREDENTIALS=/gcp/creds.json
    volumes:
    - ./creds.json:/gcp/creds.json
    - ./config.json:/app/config.json
  api:
    build: ./api
    environment:
    - GOOGLE_APPLICATION_CREDENTIALS=/gcp/creds.json
    volumes:
    - ./creds.json:/gcp/creds.json
    - ./config.json:/app/config.json
  ux:
    build: ./ux
  gateway:
    build: ./gateway
    ports:
    - 80:80