version: '3.7'
services:
  tokenerator_batch:
    build: ./batch
    image: us.gcr.io/rpg-dougrich-net/batchprocess
    environment:
    - GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/gcp_creds
    secrets:
    - gcp_creds
    - tokenerator_config
  tokenerator_api:
    build: ./api
    image: us.gcr.io/rpg-dougrich-net/tokenapi
    environment:
    - GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/gcp_creds
    secrets:
    - gcp_creds
    - tokenerator_config
    networks:
    - shared
  tokenerator_legacy:
    image: us.gcr.io/rpg-dougrich-net/legacyredirect
    build: ./legacy
    networks:
    - shared
  tokenerator_account:
    image: dougrich/oauth-aggregator
    environment:
    - AUTH_CONFIG=/run/secrets/tokenerator_auth_config
    secrets:
    - tokenerator_auth_config
    networks:
    - shared
  tokenerator_ux:
    build: ./ux
    image: us.gcr.io/rpg-dougrich-net/tokenux
    networks:
    - shared
  tokenerator_gateway:
    build: ./gateway
    image: us.gcr.io/rpg-dougrich-net/gateway
    networks:
    - shared

secrets:
  gcp_creds:
    external: true
  tokenerator_config:
    external: true
  tokenerator_auth_config:
    external: true
networks:
  shared:
    external: true