version: 2
commands:
  populate-workspace:
    description: Fetches the workspace and populates environment variables
    steps:
    - attach_workspace:
        at: /tmp/workspace
    - run: |
        bash /tmp/workspace/buildtag.sh
jobs:
  create-ids:
    machine: true
    steps:
    - run:
        name: Creating workspace
        command: |
          mkdir -p workspace
    - run:
        name: Creating readable buildid
        command: |
          BUILD_TAG=$(date '+%Y-%m-%d-')${CIRCLE_BUILD_NUM}
          echo "export BUILD_TAG=\"${BUILD_TAG}\"" >> workspace/buildtag.sh
    - persist_to_workspace:
        root: workspace
        paths:
        - buildtag.sh
  build-tokens:
    docker:
    - image: circleci/node:12
    steps:
    - checkout
    - run: |
        cd ./token-parts
        npm i
        node ./src/bundle.js
    - save_cache:
        key: token-parts-{{ .Revision }}
        paths:
        - ./api/src/token-parts.js
        - ./ux/src/token-parts.js
  build-api:
    machine:
      docker_layer_caching: true
    steps:
    - checkout
    - restore_cache:
        key: token-parts-{{ .Revision }}
        paths:
        - ./api/src/token-parts.js
    - run: echo ${GOOGLE_AUTH} > ${HOME}/gcp-key.json
    - run: docker build --rm=false -t us.gcr.io/${GCP_PROJECT}/tokenapi:${CIRCLE_SHA1} ./api
    - run: gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
    - run: gcloud --quiet config set project ${GCP_PROJECT}
    - run: gcloud docker -- push us.gcr.io/${GCP_PROJECT}/tokenapi:${CIRCLE_SHA1}
  build-ux:
    machine:
      docker_layer_caching: true
    steps:
    - checkout
    - restore_cache:
        key: token-parts-{{ .Revision }}
        paths:
        - ./ux/src/token-parts.js
    - run: echo ${GOOGLE_AUTH} > ${HOME}/gcp-key.json
    - run: docker build --rm=false -t us.gcr.io/${GCP_PROJECT}/tokenux:${CIRCLE_SHA1} ./ux
    - run: gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
    - run: gcloud --quiet config set project ${GCP_PROJECT}
    - run: gcloud docker -- push us.gcr.io/${GCP_PROJECT}/tokenux:${CIRCLE_SHA1}
  build-batch:
    machine:
      docker_layer_caching: true
    steps:
    - checkout
    - run: echo ${GOOGLE_AUTH} > ${HOME}/gcp-key.json
    - run: docker build --rm=false -t us.gcr.io/${GCP_PROJECT}/batchprocess:${CIRCLE_SHA1} ./batch
    - run: gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
    - run: gcloud --quiet config set project ${GCP_PROJECT}
    - run: gcloud docker -- push us.gcr.io/${GCP_PROJECT}/batchprocess:${CIRCLE_SHA1}
  build-gateway:
    machine:
      docker_layer_caching: true
    steps:
    - checkout
    - run: echo ${GOOGLE_AUTH} > ${HOME}/gcp-key.json
    - run: docker build --rm=false -t us.gcr.io/${GCP_PROJECT}/gateway:${CIRCLE_SHA1} ./gateway
    - run: gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
    - run: gcloud --quiet config set project ${GCP_PROJECT}
    - run: gcloud docker -- push us.gcr.io/${GCP_PROJECT}/gateway:${CIRCLE_SHA1}
  create-gcp-template:
    docker:
    - image: google/cloud-sdk
    steps:
    - populate-workspace
    - checkout
    - run: echo ${GOOGLE_AUTH} > ${HOME}/gcp-key.json
    - run: gcloud config set project ${GCP_PROJECT}
    - run: gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
    - run: 
        name: Create startup-script
        command: |
          eval "cat <<EOFF
          #/bin/bash

          useradd cloudservice
          usermod -aG docker cloudservice

          sudo -u cloudservice bash << EOF

          echo '${CONFIG}' > /home/cloudservice/config.json
          echo '${PRODUCTION_CREDS}' > /home/cloudservice/creds.json

          docker-credential-gcr configure-docker

          docker pull us.gcr.io/${GCP_PROJECT}/batchprocess:${CIRCLE_SHA1} & \
          docker pull us.gcr.io/${GCP_PROJECT}/tokenapi:${CIRCLE_SHA1} & \
          docker pull us.gcr.io/${GCP_PROJECT}/tokenux:${CIRCLE_SHA1} & \
          docker pull us.gcr.io/${GCP_PROJECT}/gateway:${CIRCLE_SHA1}

          docker network create --driver bridge tokens
          docker run -d --restart=\"always\" -v /home/cloudservice/config.json:/app/config.json -v /home/cloudservice/creds.json:/gcp/creds.json -e GOOGLE_APPLICATION_CREDENTIALS=/gcp/creds.json --network tokens --name=batch us.gcr.io/${GCP_PROJECT}/batchprocess:${CIRCLE_SHA1}
          docker run -d --restart=\"always\" -v /home/cloudservice/config.json:/app/config.json -v /home/cloudservice/creds.json:/gcp/creds.json -e GOOGLE_APPLICATION_CREDENTIALS=/gcp/creds.json --network tokens --name=api us.gcr.io/${GCP_PROJECT}/tokenapi:${CIRCLE_SHA1}
          docker run -d --restart=\"always\" -v /home/cloudservice/config.json:/app/config.json -v /home/cloudservice/creds.json:/gcp/creds.json -e GOOGLE_APPLICATION_CREDENTIALS=/gcp/creds.json --network tokens --name=ux us.gcr.io/${GCP_PROJECT}/tokenux:${CIRCLE_SHA1}
          docker run -d --restart=\"always\" -v /home/cloudservice/config.json:/app/config.json -v /home/cloudservice/creds.json:/gcp/creds.json -e GOOGLE_APPLICATION_CREDENTIALS=/gcp/creds.json --network tokens --name=gateway -p 80:80 us.gcr.io/${GCP_PROJECT}/gateway:${CIRCLE_SHA1}
          EOF

          EOFF
          " > startup-script.sh
    - run: 
        name: Create build template
        command: ./deploy/create-gcr-template.sh ${BUILD_TAG} startup-script.sh
  rolling-update:
    docker:
    - image: google/cloud-sdk
    steps:
    - populate-workspace
    - checkout
    - run: echo ${GOOGLE_AUTH} > ${HOME}/gcp-key.json
    - run: gcloud config set project ${GCP_PROJECT}
    - run: gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
    - run: 
        name: Apply rolling update
        command: ./deploy/rolling-update.sh ${BUILD_TAG}
workflows:
  version: 2
  build:
    jobs:
    - create-ids
    - build-api:
        requires:
        - build-tokens
    - build-ux:
        requires:
        - build-tokens
    - build-gateway
    - build-batch
    - create-gcp-template:
        requires:
        - build-api
        - build-batch
        - build-ux
        - build-gateway
        - create-ids
    - rolling-update:
        requires:
        - create-gcp-template
        - create-ids
        filters:
          branches:
            only: master
