version: 2
jobs:
  build-tokens:
    docker:
    - image: circleci/node:12
    steps:
    - checkout
    - run: |
        cd ./token-parts
        npm i
        node ./bundle.js
    - save_cache:
        key: token-parts-{{ .Revision }}
        paths:
        - ./api/src/token-parts.js
  build-api:
    machine:
      docker_layer_caching: true
    steps:
    - checkout
    - restore_cache:
        key: token-parts-{{ .Revision }}
        paths:
        - ./api/src/token-parts.js
    - run: echo ${GOOGLE_AUTH} > ${HOME}/gcp-key.json
    - run: docker build --rm=false -t us.gcr.io/${GCP_PROJECT}/tokenapi:${CIRCLE_SHA1} ./api
    - run: gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
    - run: gcloud --quiet config set project ${GCP_PROJECT}
    - run: gcloud docker -- push us.gcr.io/${GCP_PROJECT}/tokenapi:${CIRCLE_SHA1}
  build-batch:
    machine:
      docker_layer_caching: true
    steps:
    - checkout
    - run: echo ${GOOGLE_AUTH} > ${HOME}/gcp-key.json
    - run: docker build --rm=false -t us.gcr.io/${GCP_PROJECT}/batchprocess:${CIRCLE_SHA1} ./batch
    - run: gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
    - run: gcloud --quiet config set project ${GCP_PROJECT}
    - run: gcloud docker -- push us.gcr.io/${GCP_PROJECT}/batchprocess:${CIRCLE_SHA1}
  deploy:
    docker:
    - image: google/cloud-sdk
    steps:
    - checkout
    - run: echo ${GOOGLE_AUTH} > ${HOME}/gcp-key.json
    - run: gcloud config set project ${GCP_PROJECT}
    - run: gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
    - run: 
        name: Create startup-script
        command: |
          eval "cat <<EOFF
          #/bin/bash

          useradd cloudservice
          usermod -aG docker cloudservice

          sudo -u cloudservice bash << EOF

          echo '${CONFIG}' > /home/cloudservice/config.json

          docker-credential-gcr configure-docker

          docker run --restart=\"always\" -v /home/cloudservice/config.json:/app/config.json -d --name=batchprocess us.gcr.io/${GCP_PROJECT}/batchprocess:${CIRCLE_SHA1}
          docker run --restart=\"always\" -v /home/cloudservice/config.json:/app/config.json -d -p 80:80 --name=tokenapi us.gcr.io/${GCP_PROJECT}/tokenapi:${CIRCLE_SHA1}
          EOF

          EOFF
          " > startup-script.sh
    - run:
        name: Create build tag 
        command: |
          BUILD_TAG=$(date '+%Y-%m-%d-')${CIRCLE_BUILD_NUM}
          echo "export BUILD_TAG=\"${BUILD_TAG}\"" >> $BASH_ENV
    - run: 
        name: Create build template
        command: ./deploy/create-gcr-template.sh ${BUILD_TAG} startup-script.sh
    - run: 
        name: Apply rolling update
        command: ./deploy/rolling-update.sh ${BUILD_TAG}
workflows:
  version: 2
  build:
    jobs:
    - build-tokens
    - build-api:
        requires:
        - build-tokens
    - build-batch
    - deploy:
        requires:
        - build-api
        - build-batch