version: 2
jobs:
  build-api:
    machine: true
    steps:
    - checkout
    - run: echo ${GOOGLE_AUTH} > ${HOME}/gcp-key.json
    - run: docker build --rm=false -t us.gcr.io/${GCP_PROJECT}/tokenapi:$CIRCLE_SHA1 ./api
    - run: gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
    - run: gcloud --quiet config set project ${GCP_PROJECT}
    - run: gcloud docker -- push us.gcr.io/${GCP_PROJECT}/tokenapi:$CIRCLE_SHA1
workflows:
  version: 2
  build:
    jobs:
    - build-api