export const classTest: string;
export const token: string;
export const browse: string;
export const details: string;
export const enter: string;
export const enterActive: string;
export const leave: string;
export const leaveActive: string;
export const transitioning: string;
